apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crypto-edge.name" . }}-tenant-manager-config
  namespace: {{ include "crypto-edge.namespace" . }}
  labels:
    {{- include "crypto-edge.tenant-manager.labels" . | nindent 4 }}
immutable: {{ .Values.config.isImmutable | default false }}
data:
  config.yaml: |-
    application:
      name: {{ .Chart.Name }}
      {{- with .Values.config.application }}
      environment: {{ .environment }}
        {{- with .labels }}
      labels:
          {{- toYaml . | nindent 8 }}
        {{- end}}
      {{- end}}

      {{- with .Values.config.tenantManager }}
      {{- toYaml . | nindent 4 }}
      {{- end}}
